=== FengLucky/LubanExtend/Sample/Luban/Define/~bean.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="bean" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="module">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="bean" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="var" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute type="xs:string" name="name" use="required"/>
                                            <xs:attribute type="xs:string" name="type" use="required"/>
                                            <xs:attribute type="xs:string" name="comment" use="optional"/>
                                            <xs:attribute name="group" use="optional">
                                                <xs:simpleType>
                                                    <xs:restriction base="xs:string">
                                                        <xs:enumeration value="c"/>
                                                        <xs:enumeration value="s"/>
                                                        <xs:enumeration value="const"/>
                                                        <xs:enumeration value="comment"/>
                                                    </xs:restriction>
                                                </xs:simpleType>
                                            </xs:attribute>
                                            <xs:attribute type="xs:string" name="tags" use="optional"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="mapper" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="option" maxOccurs="2" minOccurs="2">
                                            <xs:complexType>
                                                <xs:attribute name="name" use="required">
                                                    <xs:simpleType>
                                                        <xs:restriction base="xs:string">
                                                            <xs:enumeration value="type"/>
                                                            <xs:enumeration value="constructor"/>
                                                        </xs:restriction>
                                                    </xs:simpleType>
                                                </xs:attribute>
                                                <xs:attribute type="xs:string" name="value" use="required"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="target" use="required">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:enumeration value="client"/>
                                                <xs:enumeration value="server"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                    <xs:attribute name="codeTarget" use="required">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:enumeration value="cs-bin,cs-dotnet-json,cs-simple-json"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute type="xs:string" name="name" use="required"/>
                        <xs:attribute type="xs:string" name="comment" use="optional"/>
                        <xs:attribute type="xs:boolean" name="valueType" use="optional"/>
                        <xs:attribute type="xs:string" name="sep" use="optional"/>
                        <xs:attribute type="xs:string" name="alias" use="optional"/>
                        <xs:attribute type="xs:string" name="parent" use="optional"/>
                        <xs:attribute name="group" use="optional">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="c"/>
                                    <xs:enumeration value="s"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="name" use="required"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== FengLucky/LubanExtend/Sample/Luban/Define/bean.xml
<?xml version="1.0"?>
<module
        xmlns="bean"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="bean ~bean.xsd"
        name="">
    <bean name="ClassBean" comment="class 类型">
        <var name="intField" comment="int 字段" type="int#range=[1,]"/>
        <var name="longField" comment="long 字段" type="long#range=[1,]" tags="index=multiple"/>
        <var name="floatField" comment="float 字段" type="float"/>
        <var name="doubleField" comment="double 字段" type="double"/>
        <var name="refField" comment="引用其他表id" type="int#ref=ValueTable"/>
        <var name="constField" comment="生成常量" type="string" group="const" tags="comment=stringField"/>
        <var name="stringField" comment="string 字段" type="string#path=normal;*.cs"/>
        <var name="boolField" comment="bool 字段" type="bool"/>
        <var name="setField" comment="set 字段" type="(set#sep=,),int"/>
        <var name="mapField" comment="map 字段" type="(map#sep=,),int#ref=ValueTable,int"/>
        <var name="list1" comment="list 字段,单格配置" type="(list#sep=,),int#ref=ValueTable"/>
        <var name="list2" comment="list 字段,多格配置" type="list,int#ref=ValueTable"/>
    </bean>
    <bean name="ValueBean" comment="值类型" valueType="true">
        <var name="id" comment="id" type="int"/>
    </bean>
    <bean name="InstanceBean" comment="单例配置">
        <var name="id" comment="id" type="int#ref=MapTable"/>
    </bean>
    <bean name="CfgVector3" sep="," valueType="true">
        <var name="x" type="float"/>
        <var name="y" type="float"/>
        <var name="z" type="float"/>
        <mapper target="client" codeTarget="cs-bin,cs-dotnet-json,cs-simple-json">
            <option name="type" value="System.Numerics.Vector3"/>
            <option name="constructor" value="ExternalTypeUtil.NewVector3"/>
        </mapper>
    </bean>
</module>

=== FengLucky/LubanExtend/Define/struct.xml
<?xml version="1.0"?>
<module
        xmlns="bean"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="bean ~bean.xsd"
        name="">
    <bean name="SpriteBean" comment="精灵图配置" sep="." valueType="true">
        <var name="atlas" type="string#path=normal;Atlas/*.asset" comment="图集名称" />
        <var name="sprite" type="string" comment="精灵名称"/>
    </bean>

    <bean name="JobRestraintValue" comment="职业克制加成" valueType="true">
        <var name="attack" type="int" comment="攻击加成" />
        <var name="defence" type="int" comment="防御加成" />
    </bean>
    
    <bean name="AttributeValue" comment="属性值" valueType="true">
        <var name="id" type="int#ref=AttributeTable" comment="属性id"/>
        <var name="value" type="int" comment="属性值"/>
    </bean>
    
    <bean name="CfgVector2" sep="," valueType="true">
        <var name="x" type="float"/>
        <var name="y" type="float"/>
        <mapper target="client" codeTarget="cs-bin,cs-dotnet-json,cs-simple-json">
            <option name="type" value="UnityEngine.Vector2"/>
            <option name="constructor" value="ExternalTypeUtil.NewVector2"/>
        </mapper>
    </bean>

    <bean name="CfgVector2Int" sep="," valueType="true">
        <var name="x" type="int"/>
        <var name="y" type="int"/>
        <mapper target="client" codeTarget="cs-bin,cs-dotnet-json,cs-simple-json">
            <option name="type" value="UnityEngine.Vector2Int"/>
            <option name="constructor" value="ExternalTypeUtil.NewVector2Int"/>
        </mapper>
    </bean>

    <bean name="CfgVector3" sep="," valueType="true">
        <var name="x" type="float"/>
        <var name="y" type="float"/>
        <var name="z" type="float"/>
        <mapper target="client" codeTarget="cs-bin,cs-dotnet-json,cs-simple-json">
            <option name="type" value="UnityEngine.Vector3"/>
            <option name="constructor" value="ExternalTypeUtil.NewVector3"/>
        </mapper>
    </bean>

    <bean name="CfgColor" sep="," valueType="true">
        <var name="r" type="int#range[0,255]"/>
        <var name="g" type="int#range[0,255]"/>
        <var name="b" type="int#range[0,255]"/>
        <var name="a" type="int#range[0,255]"/>
        <mapper target="client" codeTarget="cs-bin,cs-dotnet-json,cs-simple-json">
            <option name="type" value="UnityEngine.Color"/>
            <option name="constructor" value="ExternalTypeUtil.NewColor"/>
        </mapper>
    </bean>
    <bean name="CfgVerticalVertexGradient" sep="|" comment="纵向渐变颜色" valueType="true">
        <var name="top" type="CfgColor" comment="顶部颜色"/>
        <var name="bottom" type="CfgColor" comment="底部颜色"/>
        <mapper target="client" codeTarget="cs-bin,cs-dotnet-json,cs-simple-json">
            <option name="type" value="TMPro.VertexGradient"/>
            <option name="constructor" value="ExternalTypeUtil.NewVertexGradient"/>
        </mapper>
    </bean>
    <bean name="CfgHorizontalVertexGradient" sep="|" comment="横向渐变颜色" valueType="true">
        <var name="left" type="CfgColor" comment="左侧颜色"/>
        <var name="right" type="CfgColor" comment="右侧颜色"/>
        <mapper target="client" codeTarget="cs-bin,cs-dotnet-json,cs-simple-json">
            <option name="type" value="TMPro.VertexGradient"/>
            <option name="constructor" value="ExternalTypeUtil.NewVertexGradient"/>
        </mapper>
    </bean>
</module>

=== FengLucky/LubanExtend/Define/instance_bean.xml
<?xml version="1.0"?>
<module
        xmlns="bean"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="bean ~bean.xsd"
        name="">
    <bean name="CameraInstanceBean" comment="相机单例配置">
        <var name="minViewport" type="float#range[1,]" comment="横向最少展示格子"/>
        <var name="maxViewport" type="float#range[1,]" comment="横向最多展示格子"/>
        <var name="defaultViewport" type="float#range[1,]" comment="横向默认展示格子"/>
        <var name="tweenSpeed" type="float#range[0.1,]" comment="移动速度(格子/s)"/>
    </bean>
    <bean name="GameConfigBean" comment="全局配置">
        <var name="hiddenPos" type="CfgVector3" comment="池化对象隐藏位置"/>
        <var name="moveDirection" type="(list#sep=|),CfgVector2Int" comment="移动方向"/>
        <var name="initHero" type="list,int#ref=HeroTable" comment="初始英雄"/>
        <var name="killHeroMemberExpRate" type="float" comment="击杀英雄后，剩余小兵获取经验效率"/>
        <var name="cantMoveRangeColor" type="CfgColor" comment="移动时不可移动位置颜色"/>
        <var name="actorMapMoveTweenSpeed" type="float#range[0.1]" comment="角色地图移动速度(格子/s)"/>
    </bean>
</module>

=== FengLucky/LubanExtend/Define/bean.xml
<?xml version="1.0"?>
<module
        xmlns="bean"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="bean ~bean.xsd"
        name="">
    <bean name="PageBean" comment="界面配置">
        <var name="id" type="int#range=[1,]"/>
        <var name="_comment" type="string" comment="备注" group="comment"/>
        <var name="_const" type="string" comment="常量名" group="const" tags="comment=_comment"/>
        <var name="resPath" type="string#path=unity" comment="界面资源路径"/>
        <var name="holderType" type="string" comment="界面 Holder 类型"/>
        <var name="zThickness" type="int#range=[0,]" comment="z轴厚度"/>
        <var name="coverScreen" type="bool" comment="完全覆盖屏幕"/>
        <var name="alwaysInMemory" type="bool" comment="被覆盖时不销毁"/>
        <var name="multiple" type="bool" comment="可以同时存在多个"/>
    </bean>
    <bean name="AttributeBean" comment="属性配置">
        <var name="id" type="int#range=[1,]"/>
        <var name="_comment" type="string" comment="备注" group="comment"/>
        <var name="_const" type="string" comment="常量名" group="const" tags="comment=_comment"/>
        <var name="name" type="int#ref=LanguageTable" comment="属性名"/>
        <var name="maxValue" type="int#range=[0,]" comment="最大值,等于0时不限制"/>
        <var name="defaultValue" type="int#range=[0,]" comment="默认值"/>
    </bean>
    <bean name="TileBean" comment="地图块配置">
        <var name="id" type="int#range=[1,]"/>
        <var name="name" type="int#ref=LanguageTable" comment="名称"/>
        <var name="thumbnail" type="SpriteBean" comment="缩略图"/>
    </bean>
    <bean name="TileAdditionBean" comment="地形加成配置">
        <var name="id" type="int#range=[1,]"/>
        <var name="addition" type="list,int" comment="防御加成百分比，长度匹配格子表"/>
    </bean>
    <bean name="MoveCostBean" comment="移动消耗配置">
        <var name="id" type="int#range=[1,]"/>
        <var name="cost" type="list,int" comment="消耗值，长度匹配格子表"/>
    </bean>
    <bean name="JobRestraintBean" comment="职业克制加成配置">
        <var name="id" type="int#range=[1,]"/>
        <var name="addition" type="list,JobRestraintValue" comment="加成值，长度匹配职业类型"/>
    </bean>
    <bean name="LanguageBean" comment="文案配置">
        <var name="id" type="int#range[1,]"/>
        <var name="_const" type="string" comment="常量名" group="const" tags="comment=chinese"/>
        <var name="chinese" type="string" comment="中文"/>
    </bean>
    <bean name="CampBean" comment="阵营配置">
        <var name="id" type="int#range=[1,]"/>
        <var name="name" type="int#ref=LanguageTable" comment="名称"/>
        <var name="opponent" type="(list#sep=,),int#ref=CampTable" comment="对手阵营id"/>
        <var name="actorFlipX" type="bool" comment="Actor翻转x轴"/>
        <var name="actionPriority" type="int" comment="行动优先级，值越大越早行动"/>
        <var name="flagIcon" type="SpriteBean" comment="阵营图标"/>
        <var name="controlColor" type="CfgColor" comment="指挥范围颜色"/>
        <var name="actorHpColor" type="CfgVerticalVertexGradient" comment="角色生命值颜色"/>
    </bean>
    <bean name="HeroBean" comment="英雄配置">
        <var name="id" type="int#range[1,]"/>
        <var name="infoId" type="int#ref=HeroInfoTable" comment="英雄信息ID"/>
        <var name="jobId" type="int#ref=JobTable" comment="职业Id"/>
        <var name="level" type="int#range[1,]" comment="登场等级"/>
        <var name="exp" type="int#range[1,]" comment="登场经验值"/>
        <var name="soldiers" type="(list#sep=,),int#ref=JobTable" comment="登场时携带士兵"/>
        <var name="canUseSoldiers" type="(list#sep=,),int#ref=JobTable" comment="可雇佣士兵"/>
        <var name="mana" type="(list#sep=,),int#ref=ManaTable" comment="携带魔法"/>
        <var name="attribute" type="list,AttributeValue" comment="属性"/>
        <var name="controlAttribute" type="list,AttributeValue" comment="指挥属性"/>
    </bean>
    <bean name="HeroInfoBean" comment="英雄信息配置">
        <var name="id" type="int#range=[1,]"/>
        <var name="name" type="int#ref=LanguageTable" comment="名称"/>
        <var name="levelUpHead" type="SpriteBean" comment="升级时显示头像"/>
    </bean>
    <bean name="JobBean" comment="职业配置">
        <var name="id" type="int#range=[1,]"/>
    </bean>
    <bean name="ManaBean" comment="魔法配置">
        <var name="id" type="int#range=[1,]"/>
        <var name="name" type="int#ref=LanguageTable" comment="名称"/>
        <var name="costMp" type="int#range=[0,]" comment="魔力值消耗"/>
    </bean>
    <bean name="LevelBean" comment="关卡配置">
        <var name="id" type="int#range=[1,]"/>
        <var name="name" type="int#ref=LanguageTable" comment="名称"/>
    </bean>
    <bean name="LevelHeroBean" comment="关卡英雄配置">
        <var name="level" type="int#ref=LevelTable" comment="关卡Id" tags="index=multiple"/>
        <var name="hero" type="int#ref=HeroTable" comment="英雄Id"/>
        <var name="position" type="CfgVector2Int" comment="位置"/>
        <var name="camp" type="int#ref=CampTable" comment="阵营Id"/>
    </bean>
</module>
