=== FengLucky/LubanExtend/Sample/Luban/Define/~table.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="table" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="module">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="table" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:attribute type="xs:string" name="name" use="required"/>
                        <xs:attribute type="xs:string" name="value" use="required"/>
                        <xs:attribute type="xs:string" name="input" use="required"/>
                        <xs:attribute type="xs:boolean" name="readSchemaFromFile" use="optional"/>
                        <xs:attribute type="xs:string" name="index" use="optional"/>
                        <xs:attribute type="xs:string" name="comment" use="optional"/>
                        <xs:attribute type="xs:string" name="output" use="optional"/>
                        <xs:attribute name="mode" use="optional">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="list"/>
                                    <xs:enumeration value="one"/>
                                    <xs:enumeration value="map"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                        <xs:attribute name="group" use="optional">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="c"/>
                                    <xs:enumeration value="s"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="name" use="required"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== FengLucky/LubanExtend/Define/table.xml
<module
        xmlns="table"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="table ~table.xsd"
        name="">
    <table name="PageTable" value="PageBean" input="CSV/界面配置.csv"/>
    <table name="TileAdditionTable" value="TileAdditionBean" input="CSV/地形加成.csv"/>
    <table name="MoveCostTable" value="MoveCostBean" input="CSV/移动消耗.csv"/>
    <table name="JobRestraintTable" value="JobRestraintBean" input="CSV/职业克制.csv"/>
    <table name="LanguageTable" value="LanguageBean" input="CSV/Language/文案.csv"/>
    <table name="AttributeTable" value="AttributeBean" input="CSV/属性.csv"/>
    <table name="TileTable" value="TileBean" input="CSV/地图块.csv"/>
    <table name="CampTable" value="CampBean" input="CSV/阵营.csv"/>
    <table name="HeroTable" value="HeroBean" input="CSV/英雄.csv"/>
    <table name="HeroInfoTable" value="HeroInfoBean" input="CSV/英雄信息.csv"/>
    <table name="JobTable" value="JobBean" input="CSV/职业.csv"/>
    <table name="ManaTable" value="ManaBean" input="CSV/魔法.csv"/>
    <table name="LevelTable" value="LevelBean" input="CSV/关卡.csv"/>
    <table name="LevelHeroTable" value="LevelHeroBean" input="CSV/关卡英雄.csv" mode="list"/>
    
    <table name="CameraInstance" value="CameraInstanceBean" input="CSV/Instance/相机.csv" mode="one"/>
    <table name="GameConfig" value="GameConfigBean" input="CSV/Instance/全局配置.csv" mode="one"/>
    <!--
    <table name="SkillTrackTable" value="SkillTrackBean" input="Json/*@技能轨道.json"/>
    <table name="SkillAnimationTable" value="SkillAnimationBean" input="Json/*@技能动画.json"/>
    <table name="SkillReleaseTable" value="SkillReleaseBean" input="Json/*@技能打击段.json"/>
    <table name="SkillMoveTable" value="SkillMoveBean" input="Json/*@技能移动.json"/>
    <table name="SkillRotateTable" value="SkillRotateBean" input="Json/*@技能旋转.json"/>
    <table name="SkillGroupTable" value="SkillGroupBean" input="Json/*@技能组.json"/>
    -->
</module>

=== FengLucky/LubanExtend/Sample/Luban/Define/table.xml
<module
        xmlns="table"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="table ~table.xsd"
        name="">
    <table name="MapTable" value="ClassBean" input="CSV/测试.csv"/>
    <table name="OneTable" value="ValueBean" input="CSV/单例测试.csv" mode="one"/>
    <table name="InstanceTable" value="InstanceBean" input="CSV/单例测试.csv" mode="one"/>
    <table name="ListTable" value="ClassBean" input="CSV/测试.csv" mode="list"/>
    <table name="JsonTable" value="ValueBean" input="Json/*@测试.json"/>
    <table name="ValueTable" value="ValueBean" input="CSV/值测试.csv"/>
    <table name="SingleIndexMapTable" value="ClassBean" input="CSV/测试.csv" index="intField"/>
    <table name="MultiIndexMapTable" value="ClassBean" input="CSV/测试.csv" index="intField,longField"/>
    <table name="UnionIndexMapTable" value="ClassBean" input="CSV/测试.csv" index="intField+longField"/>
    <table name="SingleIndexListTable" value="ClassBean" input="CSV/测试.csv" mode="list" index="intField"/>
    <table name="MultiIndexListTable" value="ClassBean" input="CSV/测试.csv" mode="list" index="intField,longField"/>
    <table name="UnionIndexListTable" value="ClassBean" input="CSV/测试.csv" mode="list" index="intField+longField"/>
</module>
